version: '3'

networks:
  default:
    external:
      name: osv-proxy_osv_network

volumes:
  prod_media_data: { }

services:
  contracts: &contracts
    container_name: contracts
    build:
      context: .
      dockerfile: Dockerfile
    command: /app-entrypoint.sh
    volumes:
      - ./:/app
    env_file:
      - ./.envs/.api
    ports:
      - "8000"
    restart: unless-stopped
    depends_on:
      - minio
  minio:
    container_name: minio
    build:
      context: .
      dockerfile: ./services/minio/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./../.envs/.minio
    volumes:
      - prod_media_data:/data
    restart: unless-stopped