version: '3'

networks:
  network:
    driver: bridge

volumes:
  https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL
  contracts_media_data: { }

services:
  contracts: &contracts
    container_name: contracts
    build:
      context: .
      dockerfile: Dockerfile
    command: /app-entrypoint.sh
    volumes:
      - ./:/app
    env_file:
      - ./.envs/.api
    ports:
      - "8000"
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - minio
  minio:
    container_name: minio
    build:
      context: .
      dockerfile: ./services/minio/Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - ./.envs/.minio
    volumes:
      - contracts_media_data:/data
    networks:
      - network
    restart: unless-stopped
  https-portal:
    container_name: reverse_proxy
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.envs/.proxy
    volumes:
      - https-portal-data:/var/lib/https-portal
      - /var/run/docker.sock:/var/run/docker.sock:ro # DANGEROUS, see the warning above
    networks:
      - network
    restart: unless-stopped
