# Generated by Django 4.1.1 on 2022-09-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_employee_identification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='letterhead',
            field=models.ImageField(default=1, upload_to='employer/letterhead/', verbose_name='Membrete para documentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(default=1, upload_to='employer/logo/', verbose_name='Logo de la empresa'),
            preserve_default=False,
        ),
    ]
