# Generated by Django 4.1.1 on 2022-09-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_employer_letterhead_employer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contracts.city', verbose_name='Ciudad de domicilio'),
            preserve_default=False,
        ),
    ]
