# Generated by Django 4.1.1 on 2022-09-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='partner',
            field=models.CharField(default=1, max_length=600, verbose_name='Cliente principal'),
            preserve_default=False,
        ),
    ]
