# Generated by Django 4.1.1 on 2022-09-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='test_period_duration',
            field=models.CharField(default='dieciocho (18) días', max_length=100, verbose_name='Duración del periodo de prueba'),
        ),
    ]
