# Generated by Django 4.1.1 on 2022-09-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_test_period_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('description', models.TextField(default='', max_length=100000, verbose_name='Descripción de la actividad')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='activities',
            field=models.ManyToManyField(to='contracts.activity', verbose_name='Actividades especiales del contrato'),
        ),
    ]
