# Generated by Django 4.1.1 on 2022-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_activity_contract_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='letterhead',
        ),
        migrations.AddField(
            model_name='employer',
            name='letterhead_header',
            field=models.FileField(blank=True, null=True, upload_to='employer/letterhead/header/', verbose_name='Membrete para documentos (cabecera)'),
        ),
    ]
