# Generated by Django 4.1.1 on 2022-09-23 07:15

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_employer_letterhead_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='letterhead_footer',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.get_employer_upload_path, verbose_name='Membrete para documentos (pie de página)'),
        ),
    ]
