# Generated by Django 4.1.1 on 2022-09-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_employer_letterhead_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='special_activities',
            field=models.TextField(default='', max_length=100000, verbose_name='Trabajo o labor contratada'),
        ),
    ]
