# Generated by Django 4.1.1 on 2022-09-25 15:02

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contract_special_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='letterhead_footer',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='letterhead_header',
        ),
        migrations.AddField(
            model_name='employer',
            name='footer',
            field=models.ImageField(blank=True, null=True, upload_to=contracts.models.get_employer_upload_path, verbose_name='Pie de página'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=contracts.models.get_employer_upload_path, verbose_name='Logo'),
        ),
    ]
