# Generated by Django 4.1.1 on 2022-09-27 12:24

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_alter_contract_special_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='auxiliary_salary_reason',
            field=models.CharField(default='', max_length=500, verbose_name='Motivo del salario auxiliar'),
        ),
        migrations.AddField(
            model_name='contract',
            name='confidentiality_signed',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.get_employee_upload_path, verbose_name='Modelo de confidencialidad firmado'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_signed',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.get_employee_upload_path, verbose_name='Contrato firmado'),
        ),
        migrations.AddField(
            model_name='employer',
            name='consecutive_prefix',
            field=models.CharField(default='-', max_length=10, verbose_name='Prefijo del consecutivo'),
        ),
    ]
