# Generated by Django 4.1.1 on 2022-09-27 16:04

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_contract_consecutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha resignación del contrato'),
        ),
        migrations.AddField(
            model_name='contract',
            name='resignation_signed',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.get_employee_upload_path, verbose_name='Resignación firmada'),
        ),
    ]
