# Generated by Django 4.1.1 on 2022-09-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_contract_resignation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='consecutive',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='consecutive_prefix',
        ),
    ]
