# Generated by Django 4.1.1 on 2022-09-30 18:04

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_remove_contract_consecutive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=contracts.models.get_employer_upload_path, verbose_name='Firma'),
        ),
    ]
