# Generated by Django 4.1.1 on 2022-10-03 13:35

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_employer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='retirement_signed',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.get_employee_upload_path, verbose_name='Retiro voluntario firmado'),
        ),
    ]
