# Generated by Django 4.1.1 on 2022-10-06 03:55

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_contract_retirement_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='exit_exam_signed',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.get_employee_upload_path, verbose_name='Exámen de salida firmado'),
        ),
    ]
