# Generated by Django 4.1.1 on 2022-10-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_contract_exit_exam_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_entities_membership_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de afiliación a entidades'),
        ),
    ]
